# Generated by Django 6.0.7 on 2026-07-16 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='id',
            new_name='country_id',
        ),
        migrations.AddField(
            model_name='country',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_createdby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, help_text='Date Created', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_updatedby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='updateddate',
            field=models.DateTimeField(auto_now=True, help_text='Last Updated Date', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Country Name', max_length=100),
        ),
    ]
