# Generated by Django 6.0.7 on 2026-08-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='BrandID')),
                ('brand_name', models.CharField(max_length=255, unique=True, verbose_name='BrandName')),
                ('brand_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
    ]
