# Generated by Django 6.0.7 on 2026-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_code',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True, verbose_name='BrandCode'),
            preserve_default=False,
        ),
    ]
