# Generated by Django 6.0.7 on 2026-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='StoreID')),
                ('store_name', models.CharField(max_length=255, unique=True, verbose_name='StoreName')),
                ('store_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='BrandCode')),
                ('store_add', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'CO_STORES',
            },
        ),
    ]
