# Generated by Django 6.0.7 on 2026-08-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_code',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='StoreCode'),
        ),
    ]
