# Generated by Django 6.0.7 on 2026-08-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0002_brand_brand_code'),
        ('category', '0002_remove_category_parent_category_parent_id_and_more'),
        ('store', '0002_alter_store_store_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ProductID')),
                ('product_name', models.CharField(max_length=250, verbose_name='productName')),
                ('product_sku', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='productSku')),
                ('short_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='ShortDescription')),
                ('long_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='LongDescription')),
                ('product_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand', verbose_name='product_brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='product_category')),
                ('product_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='product_store')),
            ],
        ),
    ]
