# Generated by Django 6.0.7 on 2026-08-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_store',
        ),
    ]
