# Generated by Django 6.0.7 on 2026-08-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_product_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipStationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.CharField(max_length=100, unique=True)),
                ('shipment_id', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100)),
                ('carrier_id', models.CharField(max_length=100)),
                ('service_code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('shipment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('label_format', models.CharField(max_length=20)),
                ('label_pdf_url', models.URLField(max_length=500)),
                ('tracking_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipstation_label',
            },
        ),
    ]
