# Generated by Django 6.0.7 on 2026-07-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('employee', '0002_personaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country'),
        ),
    ]
