# Generated by Django 6.0.7 on 2026-07-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_department_created_by_department_updated_by_and_more'),
        ('employee', '0005_remove_employees_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='department.department'),
        ),
    ]
