# Generated by Django 6.0.7 on 2026-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employees_department'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='TestPersonalDetails',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('phone_number', models.CharField(max_length=15)),
        #     ],
        # ),
    ]
