# Generated by Django 6.0.7 on 2026-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_testpersonaldetails'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='testpersonaldetails',
        #     name='phone_number',
        #     field=models.CharField(max_length=25),
        # ),
    ]
