# Generated by Django 6.0.7 on 2026-07-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_testpersonaldetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPersonalDetails',
        ),
    ]
