# Generated by Django 6.0.7 on 2026-08-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_table'),
        ('store', '0002_alter_store_store_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='InventoryID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Store')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
