# Generated by Django 6.0.7 on 2026-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_created_at_department_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
